// B.9 / K-55 — 知识域 API 层拆分后的 barrel（唯一对外入口）。
//
// 原 1,299 行单文件已按 Tab 拆为 services/api/{overview,assets,extract,graph,wiki,govern}.ts
// + api/base.ts（base 常量单源）。本文件不保留任何函数实现，仅：
//   1. `export *` 逐模块转导出全部函数 / 接口 / 类型 → 对外符号集与拆分前完全一致（API 只增不改）；
//   2. 重建 `knowledgeApi` / `wave3c1C1Api` 两个合并对象（成员集合与拆分前逐项相同）。
// 23 处消费方 `import { ... } from '.../knowledgeApi'` 的符号路径不受影响。
import {
  fetchGraph,
  fetchNode,
  searchKnowledge,
  findPath,
  graphSearch,
  graphPath,
  fetchNeighbors,
  createNode,
  createEdge,
  getDataSource,
  fetchSyncStatuses,
  triggerFullSync,
  triggerObjectSync,
  fetchSyncLogs,
  fetchGraphJobs,
  previewGraphBuild,
  triggerGraphBuild,
  previewGraphJob,
  rollbackGraphJob,
  fetchGraphJobLogs,
  fetchIndexStatus,
  syncVectors,
} from './api/graph';
import {
  fetchGraphStats,
  fetchEntityMappings,
  fetchEngineHealth,
} from './api/overview';
import {
  fetchGlossaryTerms,
  createGlossaryTerm,
  updateGlossaryTerm,
  deleteGlossaryTerm,
  classifyAsset,
  fetchCognitiveConfig,
  updateCognitiveConfig,
  fetchLineageImpact,
  parseLineage,
  fetchIntegrationMetadata,
  fetchIntegrationLogs,
  toggleSimulationDrift,
  fetchRules,
  createRule,
  updateRule,
  deleteRule,
  fetchRuleVersions,
  fetchOntologyMappings,
  saveOntologyMappings,
  exportOntology,
} from './api/wiki';
import {
  fetchNavProductsByCategory,
  getSettings,
  updateSettings,
  fetchEvalSeeds,
  uploadEvalSeed,
  runEval,
  fetchLifecycleAssets,
  lifecycleTransition,
  fetchLifecycleAudit,
  fetchDataWorkbenchSources,
  fetchMetadataDrift,
} from './api/assets';
import {
  runRAGQuerySSE,
  runRAGQuery,
  runKnowledgeQuery,
  fetchEngineConfig,
  saveEngineConfig,
} from './api/govern';
import {
  fetchImportQueue,
  addImportToQueue,
  retryImport,
  uploadDocumentChunked,
  fetchExtractCandidates,
  fetchUploadEnabled,
  fetchTriggerStructuredExtract,
  fetchStructuredJobs,
  fetchStructuredJobDetail,
  fetchExtractEngineConfig,
  fetchExtractCandidateFiles,
  fetchOntologyTree,
  fetchScheduledExtracts,
  createScheduledExtract,
  updateScheduledExtract,
  deleteScheduledExtract,
  fetchExtractLogs,
  fetchExportLogBody,
  triggerStructuredExtract,
  fetchExtractStatus,
  fetchExtractJobs,
  fetchExtractJobStatus,
  createScheduledExtractRow,
  updateScheduledExtractRow,
  exportExtractLog,
} from './api/extract';

// ── 全量转导出（含全部接口 / 类型对外符号） ─────────────────────────────────
export * from './api/base';
export * from './api/graph';
export * from './api/overview';
export * from './api/wiki';
export * from './api/assets';
export * from './api/govern';
export * from './api/extract';

// ── Wave 3 C1 api 导出（追加，不影响 knowledgeApi 对象内既有成员） ─────────
export const wave3c1C1Api = {
  fetchOntologyTree,
  fetchExtractJobs,
  fetchExtractJobStatus,
  fetchScheduledExtracts,
  createScheduledExtractRow,
  updateScheduledExtractRow,
  deleteScheduledExtract,
  fetchExtractLogs,
  exportExtractLog,
};

// ── PMO-54 — Consolidated knowledgeApi export (extended with above) ──────────
export const knowledgeApi = {
  fetchGraph,
  fetchNode,
  searchKnowledge,
  findPath,
  graphSearch,
  graphPath,
  fetchNeighbors,
  createNode,
  createEdge,
  getDataSource,
  fetchSyncStatuses,
  triggerFullSync,
  triggerObjectSync,
  fetchSyncLogs,
  fetchOntologyMappings,
  saveOntologyMappings,
  exportOntology,
  fetchIndexStatus,
  syncVectors,
  runRAGQuery,
  runRAGQuerySSE,
  runKnowledgeQuery,
  fetchNavProductsByCategory,
  getSettings,
  updateSettings,
  fetchGlossaryTerms,
  createGlossaryTerm,
  updateGlossaryTerm,
  deleteGlossaryTerm,
  classifyAsset,
  fetchCognitiveConfig,
  updateCognitiveConfig,
  fetchLineageImpact,
  parseLineage,
  fetchIntegrationMetadata,
  fetchIntegrationLogs,
  toggleSimulationDrift,
  fetchRules,
  createRule,
  updateRule,
  deleteRule,
  fetchRuleVersions,
  // PMO-54
  fetchGraphStats,
  fetchEntityMappings,
  fetchEngineHealth,
  fetchGraphJobs,
  previewGraphBuild,
  triggerGraphBuild,
  previewGraphJob,
  rollbackGraphJob,
  fetchGraphJobLogs,
  fetchImportQueue,
  addImportToQueue,
  retryImport,
  uploadDocumentChunked,
  fetchExtractCandidates,
  fetchUploadEnabled,
  fetchTriggerStructuredExtract,
  fetchStructuredJobs,
  fetchStructuredJobDetail,
  fetchExtractEngineConfig,
  fetchExtractCandidateFiles,
  fetchEvalSeeds,
  uploadEvalSeed,
  runEval,
  fetchLifecycleAssets,
  lifecycleTransition,
  fetchLifecycleAudit,
  fetchEngineConfig,
  saveEngineConfig,
  fetchDataWorkbenchSources,
  fetchMetadataDrift,
  // Wave 3 C1 — T8 本体树 / 定时抽取 / 日志 / 状态
  fetchOntologyTree,
  fetchScheduledExtracts,
  createScheduledExtract,
  updateScheduledExtract,
  deleteScheduledExtract,
  fetchExtractLogs,
  fetchExportLogBody,
  triggerStructuredExtract,
  fetchExtractStatus,
};
