/**
 * @license
 * SPDX-License-Identifier: Apache-2.0
 */

import React, { createContext, useContext, useState, useEffect } from "react";

export type Locale = "zh" | "en";

interface LanguageContextType {
  locale: Locale;
  setLocale: (locale: Locale) => void;
  t: (key: string) => string;
}

const DICTIONARY: Record<Locale, Record<string, string>> = {
  zh: {
    // Brand
    "brand.title": "C2EOS 认知决策核",
    "brand.kernel": "认知内核 v15.1",

    // Sidebar navigation groups
    "nav.group.primary": "协同调度中心",
    "nav.group.data_platform": "数据基础平台",
    "nav.group.knowledge": "语义智层 (本体)",
    "nav.group.aip": "AIP 智能体控制器",
    "nav.group.security": "安全与合规治理",
    "nav.group.marketplace": "数据市场",

    // Sidebar navigation items
    "nav.item.mission_control": "主控协同大盘",
    "nav.item.mission_control.desc": "ECOS 协同认知决策大盘",
    "nav.item.catalog": "数据资产目录",
    "nav.item.catalog.desc": "全域资产元数据检索列表",
    "nav.item.explorer": "数据集浏览器",
    "nav.item.explorer.desc": "表结构预览、分区与质量监控",
    "nav.item.lineage": "智能数据血缘",
    "nav.item.lineage.desc": "全谱系数据流向与影响拓扑图",
    "nav.item.pipeline": "流水线构建器",
    "nav.item.pipeline.desc": "Spark作业有向无环图(DAG)配置",
    "nav.item.workbook": "Code Workbook",
    "nav.item.workbook.desc": "编写 Python/SQL、生成分析图表与建模",
    "nav.item.ontology": "本地本体管理器",
    "nav.item.ontology.desc": "语义知识、属性绑定与完整性校验",
    "nav.item.ops_apps": "业务工作区",
    "nav.item.ops_apps.desc": "基于本体和智能体的一线操作控制台",
    "nav.item.monitor": "监控决策总控制台",
    "nav.item.monitor.desc": "全系统健康大盘与数据质量监控雷达",
    "nav.item.agent": "多智能体工坊",
    "nav.item.agent.desc": "垂直Agent协同决策调优及Trace",
    "nav.item.security": "访问准入与审计",
    "nav.item.security.desc": "RBAC准入策略及不可篡改区块审计",

    // Sidebar footer
    "sidebar.status": "内核运行状态",
    "sidebar.status.optimal": "极其良好",
    "sidebar.spark_jobs": "活跃 Spark 作业",
    "sidebar.spark_jobs.active": "个正在运行",
    "sidebar.latency": "认知引擎总延迟",

    // Topbar
    "topbar.admin": "决策总指挥官",
    "topbar.role": "4级高阶授权专家",
    "topbar.palette": "输入快捷指令 (Ctrl+K)...",
    "topbar.c2eos": "認知核心",
    "topbar.user.settings": "用户配置设置",
    "topbar.user.email": "电子邮箱",
    "topbar.user.clearance": "安全准入等级",
    "topbar.user.workstation": "绑定物理工作站",
    "topbar.user.auditlevel": "双写审计力度",
    "topbar.user.auditlevel.full": "基于ABAC的不可篡改密码学全域审计",
    "topbar.user.auditlevel.standard": "仅存留普通事件控制台历史记录",
    "topbar.user.sandbox": "强制启动高危指令智能体沙盒审查",
    "topbar.user.reset": "清空工作空间状态缓存",
    "topbar.user.reset.success": "核心工作区组件状态及日志缓存成功清空！",
    "topbar.user.save": "保存并重连核准通道",
    "topbar.user.save.success": "配置文件已写入本地内核缓存，通信通道双向热重连完成！",

    // Breadcrumbs
    "bc.cognitive_core": "认知核心层",
    "bc.mission_control": "全景协同中心",
    "bc.data_platform": "数据大平台",
    "bc.data_catalog": "元数据资产检索",
    "bc.datasets_explorer": "明细表格分析",
    "bc.lineage_graph": "多节点数据血缘",
    "bc.pipeline_dag": "Spark有向无环流水线",
    "bc.knowledge_layer": "知识本体层",
    "bc.ontology_manager": "概念本体拓扑分析",
    "bc.cognitive_layer": "高认知行动层",
    "bc.aip_agent_studio": "多Agents开发控制台",
    "bc.security_audit": "合规审计卫士",
    "bc.access_policies": "RBAC安全策略审查",
    "bc.system": "支撑系统",
    "bc.workspace": "多维工作空间",

    // Pages common / general
    "btn.close": "关闭",
    "btn.cancel": "取消",
    "btn.submit": "提交操作指令",

    // 1. CognitiveOperatingSystem (Mission Control)
    "cos.title": "C2EOS 企业级智能认知决策总控室",
    "cos.desc": "敏锐洞察全谱系根因，运行全模拟数字孪生运行沙盘，推演多目标最优帕累托前沿 (Pareto Frontier) 行动导则。",
    "cos.simulating": "ECOS 执行沙盘多维演练中...",
    "cos.btn.simulate": "执行数字沙盘决策模拟推演",
    "cos.kpi.rev": "总营收最大化目标",
    "cos.kpi.rev.status": "存在偏离风险",
    "cos.kpi.rev.target": "营收底线目标: >$1.1B",
    "cos.kpi.delay": "工厂机械总延迟率",
    "cos.kpi.delay.status": "处于落后状态",
    "cos.kpi.delay.target": "底线控制目标: <2.0%",
    "cos.kpi.safety": "HSE全员零安全事故",
    "cos.kpi.safety.status": "安全绿色完好",
    "cos.kpi.safety.target": "零风险运营",
    "cos.kpi.safety.val": "0 级重大隐患",
    "cos.graph.title": "ECOS 企业全景因果传导图象",
    "cos.graph.btn.pareto": "激活帕累托多重目标寻优算法",
    "cos.graph.pareto.title": "ECOS 帕累托决策多目标进化锋面",
    "cos.graph.node.inspect": "选定因果事件根因剖析",
    "cos.graph.node.weight": "因果相互传导权重:",
    "cos.graph.node.cause": "根因触发因子:",
    "cos.graph.node.effect": "直接级联效应:",
    "cos.graph.node.explain": "传导效应解读:",
    "cos.sim.sandbox": "企业决策多维孪生沙箱演算",
    "cos.sim.scenario": "选择模拟演练情境:",
    "cos.sim.outage": "计划外检修中断时长 (小时):",
    "cos.sim.extra": "新增应急维保班次-排班频次/周:",
    "cos.sim.output": "决策模拟演算终端输出:",
    "cos.sim.idle": "数字仿真引擎空闲。请点击上方【执行决策推演】按钮开始装载数据。",

    // 2. DataCatalog (Data Catalog)
    "catalog.title": "企业数据资产元数据索引库",
    "catalog.desc": "检索注册在 ECOS 内的所有结构化数据资产，包括数据源库、本体映射状态和业务合规指标。",
    "catalog.placeholder": "按名称、部门、标签、数据表结构搜索全域元数据...",
    "catalog.btn.register": "注册全新物理存储数据表 (DDL/JDBC)",
    "catalog.meta.summary": "当前元数据列表集成",
    "catalog.meta.assets": "存储对象",
    "catalog.col.asset": "物理数据资产",
    "catalog.col.type": "资产类型",
    "catalog.col.quality": "质量评分",
    "catalog.col.domain": "业务域",
    "catalog.col.rows": "行数规模",
    "catalog.col.updated": "血缘近演更新时间",
    "catalog.btn.explore": "跳转明细浏览器",

    // 3. DatasetExplorer
    "db.back": "返回数据资产目录",
    "db.desc": "检视表结构、评估探查分析和即时安全控制。",
    "db.tab.schema": "表字段物理 Schema",
    "db.tab.data": "明细数据抽样预览",
    "db.tab.rules": "数据质量探查拦截规约",
    "db.tab.lineage": "端到端元数据流向血缘",
    "db.quality_rules": "当前表部署的数据质量规则",
    "db.columns": "列",
    "db.rows": "行",
    "db.size": "磁盘占用",
    "db.col.field": "字段名称",
    "db.col.type": "物理类型",
    "db.col.quality": "字段级质量评分",
    "db.col.desc": "业务含义注解说明",
    "db.rules.rule": "智能监控判定规则",
    "db.rules.type": "监控质检项类别",
    "db.rules.status": "当前校验结果",
    "db.lineage.info": "当前表上游产出和下游引用，任何结构变动将触发级联编译警报。",

    // 4. PipelineBuilder
    "pb.title": "流水线有向无环图作业工坊",
    "pb.desc": "以视觉拓扑方式装配、测试及编译 Spark 大型批处理数据链路。",
    "pb.compiling": "SPARK 流水线执行内核编译运行中...",
    "pb.btn.compile": "全域编译并驱动 DAG 流水线",
    "pb.editor.title": "Visual Node DAG 流水线拖拽设计器",
    "pb.editor.authoritative": "已连接工作区编译缓存",
    "pb.sidebar.title": "DAG 节点物理配置器",
    "pb.sidebar.node_type": "节点算子物理类别",
    "pb.sidebar.sql": "数据流向聚合/变换 SQL 逻辑式",
    "pb.sidebar.namespace": "接收写入的命名空间文件",
    "pb.sidebar.empty": "请在左侧点击任一 DAG 任务节点以配置其 Spark 逻辑属性。",

    // 5. OntologyExplorer
    "ont.title": "概念本体管理器与行动驱动核",
    "ont.desc": "将基础物理数据库抽象包装为语义知识对象，构建多维度因果联系图谱，赋予行动核自动化决策指令。",
    "ont.loading": "加载中...",
    "ont.load_error": "本体数据加载失败",
    "ont.btn.define": "加载全新实体/行为规则 (YAML DSL)",
    "ont.sidebar.title": "注册激活本体对象",
    "ont.workbench.title": "概念本体物理绑定特征与结构模型",
    "ont.workbench.props": "属性及基本数据特征绑定名录",
    "ont.workbench.rel": "实体、行为关联外键依存约束谱",
    "ont.workbench.required": "必需项",
    "ont.workbench.constraint": "参照完整性约束：ECOS 微服务内核提供全局事务防爆隔离。",
    "ont.workbench.actions": "该本体已注册的安全运营干预指令",
    "ont.workbench.form_active": "行动调试智能交互面板:",
    "ont.workbench.high_impact": "高危操作",
    "ont.workbench.topo": "概念本体语义多维连通性关系图谱",

    // 6. AgentStudio
    "agent.title": "多Agent智能体协同调度控制器",
    "agent.desc": "装配多智能体自主分工执行链条。支持编辑提示词沙盒、调试工具函数注册、查看OpenTelemetry执行细节Trace。",
    "agent.btn.eval": "启动智能体全流程反思与链路追踪",
    "agent.sidebar.agents": "工坊就绪的专属智能体角色",
    "agent.sidebar.tools": "开放给 Agent 运行调用的工具库",
    "agent.sandbox.title": "智能开发者 Prompt 实战沙盘",
    "agent.sandbox.filepath": "文件路径:",
    "agent.sandbox.version": "当前 Prompt 调优版本:",
    "agent.trace.title": "AIP 链路全追溯 OpenTelemetry Trace 观测终端",
    "agent.trace.under": "全局遵循 OpenTelemetry 高性能遥测规范",
    "agent.trace.idle": "遥测追踪器空闲。请点击右上角【启动全流程反思】按钮生成 Agent 思考链路 Trace日志。",
    "agent.gauges.title": "AI 运行成本与协同效益大盘",
    "agent.gauges.success": "推理任务吞吐质检极佳率",
    "agent.gauges.tokens": "模型当前会话累计 Tokens 消耗",
    "agent.gauges.dollars": "会话产生的估算 API 账单金额",
    "agent.gauges.tools_count": "自主工具函数调用频数",
    "agent.gauges.warn": "配额限制警告",
    "agent.gauges.warn_desc": "大语言模型及多智能体 API 账户余额与全区资源配额挂钩。",

    // 7. SecurityAudit
    "sec.title": "多租户多角色准入审查与区块索引日志",
    "sec.desc": "基于全生命周期不可篡改审计追踪验证策略。执行精细化行/列级数据规则(RBAC)。",
    "sec.btn.add": "配置生成并分发安全合规防护准则",
    "sec.meta.active": "安全卫士已拦截保障",
    "sec.meta.event": "全流程审计区块",
    "sec.meta.rule": "行级与列级隔离准则",
    "sec.tb.audit_title": "基于不可篡改账本保护的全局操作审计区块日志",
    "sec.tb.col.time": "行为发生时间",
    "sec.tb.col.actor": "操作主体 (账号)",
    "sec.tb.col.action": "指令行为",
    "sec.tb.col.target": "客体对象",
    "sec.tb.col.details": "核心 payload & trace 签名校验",
    "sec.tb.col.status": "安全判定状态",
    "sec.tb.status.success": "校验无误安全放行",
    "sec.tb.status.pending": "审计合规待批",
    "sec.rbac.title": "基于业务角色的精细化行列级访问隔离防护策略(RBAC)",
    "sec.rbac.col.target": "作用客体数据",
    "sec.rbac.col.rule": "安全特许准则",

    // New keys for DatasetExplorer detail views
    "db.stats.title": "命名空间统计指标",
    "db.stats.rows": "物理数据行数",
    "db.stats.cols": "字段数量",
    "db.stats.size": "逻辑存储容量",
    "db.stats.quality": "质量评级水位",
    "db.history.title": "数据集版本审计历史",
    "db.history.empty": "当前命名空间无历史版本审计记录。",
    "db.meta.title": "系统元数据属性",
    "db.meta.domain": "所属业务域",
    "db.meta.tags": "关联系统标签",
    "db.permissions.title": "ACL 访问控制列表",
    "db.permissions.owner": "管理所有者 (Owner)",
    "db.permissions.editor": "授权编辑者 (Editor)",
    "db.permissions.viewer": "默认读取者 (Viewer)",
    "db.fields.title": "数据字段映射集",
    "db.fields.col_field": "字段属性名",
    "db.fields.col_type": "数据类型",
    "db.fields.col_null": "是否为空",
    "db.fields.col_quality": "质量评分",
    "db.inspector.title": "元数据字段详情检视",
    "db.inspector.type": "字段物理类型",
    "db.inspector.nullability": "可空性约束校验",
    "db.inspector.null_yes": "允许为空 NULL (可选字段)",
    "db.inspector.null_no": "强制非空 NOT NULL (主键必填)",
    "db.inspector.semantics": "业务语义及注释说明",
    "db.inspector.empty_semantics": "资产目录中未登记此字段的业务语义。",
    "db.inspector.quality": "属性质量校验水位",
    "db.inspector.quality_desc": "通过持续回归规则校验。未检测到空指针违规或孤立关联。",
    "db.inspector.empty": "请在左侧列表中选择任一字段以显示其语义属性。",
    "db.inspector.policy": "该规则集由本体定义层安全策略保护",
    "db.preview.title": "事务预览抽样 (展示 limit)",
    "db.preview.desc": "已执行物理表可读限制，仅调取、预览前 100 行记录",
    "db.preview.sql": "等效 SQL 查询式: ",
    "db.quality.active_rules": "当前激活的数据质量校验规则集",
    "db.quality.method": "质检监控方式: ",
    "db.quality.health_grade": "数据完整性综合健康评级",
    "db.quality.certified": "由于该物理表顺利通过所有核心非空校验、边界范围约束及去重模型测试，已由系统标记为【特许专家级免检免灾资产】，完全符合大模型训练及企业经营管理决策的最高可信标准。",
    "db.quality.caution": "注意警告: 生产控制系统的温度传感器检测到超出阈值的极限过热尖峰，在日级 Spark 流水线数据摄入和对账循环中，识别出 3 个异常物理离群值，请尽快检查传感器接口规范并激活旁路拦截行动。",
    "db.lineage.centered": "当前以物理资产为核心的交互式血缘关系连通性图表: ",

    // New keys for SecurityAudit detail views
    "sec.ledger.title": "基于不可篡改账本保护的全局操作审计区块日志 (密码学签名)",
    "sec.ledger.subtitle": "实时遥测流数据",
    "sec.ledger.voucher": "凭证编号: ",
    "sec.ledger.committed": "已提交 (Committed)",
    "sec.ledger.pending": "审计待签批 (Pending Signoff)",
    "sec.directives.title": "安全指令及行/列控制规则",
    "sec.directives.subtitle": "基于上下文属性的ABAC授权规则",
    "sec.directives.desc": "在编译阶段强制执行精细化的数据集访问限制。根据员工角色约束动态过滤字段/物理分区。",
    "sec.directives.policy_label": " 安全策略",
    "sec.directives.scope_class": " 作用域类别",
    "sec.directives.condition": "激活判定条件: ",
    "sec.directives.unlimited": "无条件完全访问",
    "sec.bounds.title": "安全合规审计边界保护",
    "sec.bounds.desc": "ECOS 元数据层严格控制数据库表的互通关联，动态确保符合 SOX、GDPR、数据安全法及企业级隔离规范制度要求。",

    // New keys for OntologyExplorer details
    "ont.blueprint.title": "概念本体语义绑定特征与结构模型 Blueprint",
    "ont.blueprint.object_suffix": " 语义实体类别",
    "ont.properties.required": "必需项",
    "ont.actions.title": "该本体已注册的安全干预指令 (Ontology Actions)",
    "ont.form.title": "行动调试智能交互面板: ",
    "ont.form.close": "关闭面板 (X)",
    "ont.form.cancel": "取消执行",
    "ont.form.placeholder_true": "真值 True (已启用)",
    "ont.form.placeholder_false": "假值 False (已禁用)",
    "ont.workbench.toast_fail": "高危行为已被拦截保护: 动态沙箱已注册该合规准则并升入系统安全审计流程，待管理员二次会签。",
    "ont.workbench.toast_success": "指令操作提交成功！审计及物理日志已落盘入区块。",
    "ont.workbench.alert_prompt": "本体可视化编辑属于系统核心架构级权限。如需发布或修改 YAML DSL 双向契约，请联系系统超级管理员。",
    "ont.workbench.submit_btn": "执行该项行动",
    "ontology_designer.confirm_delete": "删除实体会同时删除其属性和关系，确认？",
    "object_explorer.confirm_delete": "确定删除此对象？",

    // GlossaryManager
    "glossary.title": "术语库",
    "glossary.unit": "条",
    "glossary.all": "全部",
    "glossary.search_placeholder": "搜索术语名称...",
    "glossary.new_term": "新建术语",
    "glossary.loading": "加载中...",
    "glossary.no_match": "未找到匹配",
    "glossary.empty": "暂无术语，点击上方「+ 新建术语」开始创建",
    "glossary.empty_hint": "点击「+ 新建术语」开始，或从左侧选择一个术语查看详情",
    "glossary.term_detail": "术语详情",
    "glossary.edit": "编辑",
    "glossary.delete": "删除",
    "glossary.save": "保存",
    "glossary.cancel": "取消",
    "glossary.actions": "操作",
    "glossary.delete_confirm_title": "确认删除",
    "glossary.delete_confirm_msg": "确定要删除术语「{name}」吗？此操作不可撤销。",
    "glossary.field.name": "术语名称",
    "glossary.field.name_placeholder": "例如：数据血缘",
    "glossary.field.domain": "领域",
    "glossary.field.domain_placeholder": "选择领域",
    "glossary.field.definition": "定义",
    "glossary.field.definition_placeholder": "描述该术语的含义...",
    "glossary.field.status": "当前状态",
    "glossary.status.draft": "草稿",
    "glossary.status.review": "审核",
    "glossary.status.published": "已发布",
    "glossary.transition.submit_review": "提交审核",
    "glossary.transition.publish": "发布",
    "glossary.transition.deprecate": "废弃",
    "glossary.toast.load_failed": "加载失败",
    "glossary.toast.name_required": "术语名称不能为空",
    "glossary.toast.created": "术语创建成功",
    "glossary.toast.updated": "术语更新成功",
    "glossary.toast.save_failed": "保存失败",
    "glossary.toast.status_changed": "状态已变更为",
    "glossary.toast.status_failed": "状态变更失败",
    "glossary.toast.deleted": "已删除",
    "glossary.toast.delete_failed": "删除失败",

    "theme.label": "界面样式",
    "theme.slate-light": "石板雅白 (明亮)",
    "theme.deep-space": "智蓝星空 (暗黑)",
    "theme.cyber-terminal": "极客终端 (炫绿)",
    "theme.royal-purple": "皇家幽紫 (高贵)",

    // 8. Code Workbook keys
    "wb.title": "Code Workbook",
    "wb.desc": "物理/逻辑数据特征分析，支持 Python、SQL 多代码块组合即时仿真与动态计算。",
    "wb.sidebar.header": "数据分析架构模型",
    "wb.active.dfs": "已加载的 DataFrames",
    "wb.active.dfs.rows": "行",
    "wb.active.dfs.cols": "字段",
    "wb.stream.mappings": "流处理与存储映射",
    "wb.runtime": "交互工作台运行时",
    "wb.memory": "内存分配 32GB (正常运行)",
    "wb.run.all": "运行全套工作流 (Spark)",
    "wb.active.cell": "单元格",
    "wb.active.idle": "未修改执行",
    "wb.active.success": "SUCCESS (1.2秒)",
    "wb.active.running": "COMPILING SPARK EXEC...",
    "wb.active.outputs": "探查输出 (Outputs)",
    "wb.active.outputs.placeholder": "点击运行单元格生成多指标可视化",

    // 9. Operational Applications keys
    "ops.title": "业务工作区",
    "ops.desc": "融合语义本体(Ontology)双向对齐的大模型与一线生产决策决策操作总控室。任何操作将受到不可篡改审计日志实时追踪。",
    "ops.tab.crm": "客户风险与授信",
    "ops.tab.maint": "工况智能调度",
    "ops.tab.fin": "账单对账与审计",
    "ops.crm.header": "全链条客户信用与授权管理应用 (Slate)",
    "ops.crm.select": "选择目标客户实体 Class",
    "ops.crm.status": "经营状态",
    "ops.crm.revenue": "总计年度收入 (Revenue)",
    "ops.crm.region": "业务划分区域",
    "ops.crm.region.sea": "海运中心",
    "ops.crm.churn": "流失危险率 (Churn index)",
    "ops.crm.control.credit": "授信信用提额分配",
    "ops.crm.control.credit.btn": "调整授信",
    "ops.crm.control.credit.hint": "安全提示：增信额度大于 $5,000,000 USD 会自动转入风控决策链会签。",
    "ops.crm.control.freeze": "高危安全防护隔离",
    "ops.crm.control.freeze.btn": "紧急终止交易通道 (Freeze)",
    "ops.crm.control.freeze.hint": "此动作为高危操作。一键启动会导致下游 CRM 系统及订单系统立即暂停结算。",
    "ops.maint.header": "工况温度及机械故障应急干预终端 (Workshop)",
    "ops.maint.col.id": "机组编号",
    "ops.maint.col.temp": "热敏温度 (Core Temp)",
    "ops.maint.col.status": "判定状态",
    "ops.maint.col.action": "紧急干预行动",
    "ops.maint.action.btn": "派发应急抢修凭证",
    "ops.maint.action.ok": "机组运行平稳",
    "ops.maint.settings": "抢修派工属性设置",
    "ops.maint.priority": "维保抢修优先等级",
    "ops.maint.note": "附言 / 维保机组指令",
    "ops.maint.note.placeholder": "例如: 轴承过热，派遣3号工程班次",
    "ops.fin.header": "财务对账及 Escrow 托管大额审批阀门 (Secure Slate)",
    "ops.fin.warning.title": "超出自动化对账限制",
    "ops.fin.warning.desc": "在对账计算中，系统发现存在单笔金额超过审计安全底线 ($1,500,000 USD) 的 Pending 状态订单。依据金融合规审查，该条目已自动升级并由 ECOS 认知网格中进行多智能体验证追踪。",
    "ops.fin.detail.id": "待审批交易摘要 ID:",
    "ops.fin.detail.client": "交易对手 / 承购方:",
    "ops.fin.detail.amount": "交易结算金额:",
    "ops.fin.btn.approve": "双签授权合规通过",
    "ops.fin.btn.reject": "拒绝并拉起风控",
    "ops.panel.title": "Ontology 语义本体模型交互优势",
    "ops.panel.p1": "不同于底层的传统粗糙数据库，本系统已将 Customer / Facility 数据库映射为全局逻辑本体 Class。",
    "ops.panel.p2.title": "Double-write Ledger:",
    "ops.panel.p2.desc": "系统在通过 API 提交修改动作时，会同步调用行级 ABAC 机制判定规则，核实操作主体的合规身份，拒绝伪造注入。",
    "ops.panel.p3.title": "Uniqueness signature:",
    "ops.panel.p3.desc": "任一高危业务行动触发，即会自动在 Security Center (访问准入与审计) 生成由大模型及系统双向签名的密码学操作凭证，永久沉淀至不可篡改账本上。",

    // 10. Monitoring Center keys
    "mon.title": "监控决策总控制台",
    "mon.desc": "实时物理基础设施负载、Spark 批处理性能指标、数据流监控与全域数据质量自检中心。",
    "mon.btn.diag": "全域诊断自检 (Telemetry)",
    "mon.diag.success": "DIAGNOSTIC_COMPLETED: CDRC MySQL 数据库连接池状态完好。Spark 批处理流计算 DAG 算子拓扑链状态检查：无死锁、无分区延迟。安全双写语义本体规规约规则判定合规。检测到 0 处孤立无效记录。",
    "mon.kpi.cpu": "C2EOS 内核 CPU 负载",
    "mon.kpi.cpu.desc": "16核已分配虚拟机",
    "mon.kpi.mem": "高吞吐内存分配",
    "mon.kpi.mem.desc": "已用 / 物理可用组容量 32GB",
    "mon.kpi.spark": "Spark 流数据摄入率",
    "mon.kpi.spark.desc": "连续低延迟微批次接收",
    "mon.kpi.db": "MySQL 连接通道状态",
    "mon.kpi.db.desc": "连接池活动数: 24/100",
    "mon.chart.title": "全域批/流一体 Spark Ingest 数据吞吐速率测速 (Packets/sec)",
    "mon.daemon.title": "后台持续执行状态及活跃守护进程 (Daemons)",
    "mon.daemon.col.job": "守护进程 / Active Jobs",
    "mon.daemon.col.type": "物理类别",
    "mon.daemon.col.uptime": "连续运行时间",
    "mon.daemon.col.count": "已校验数据对账行数",
    "mon.rules.title": "实时元数据质量警报日志",

    // 11. Workflow Designer
    "wf.title": "流程设计器",
    "wf.desc": "拖拽式可视化流程设计，支持 Agent 节点嵌入",
    "wf.btn.create": "新建流程",
    "wf.btn.save": "保存",
    "wf.btn.publish": "发布",
    "wf.btn.test": "测试",
    "wf.btn.back": "返回列表",
    "wf.btn.close": "关闭",
    "wf.status.published": "已发布",
    "wf.status.draft": "草稿",
    "wf.node_type.start": "开始",
    "wf.node_type.end": "结束",
    "wf.node_type.human_task": "人工任务",
    "wf.node_type.agent_node": "Agent节点",
    "wf.node_type.condition_gateway": "条件网关",
    "wf.palette.title": "节点库",
    "wf.designer.untitled": "未命名流程",
    "wf.designer.no_name": "未命名",
    "wf.panel.label": "节点名称",
    "wf.panel.assignee": "分配人",
    "wf.panel.agent_role": "Agent 角色",
    "wf.panel.tools": "工具选择",
    "wf.panel.input_map": "输入映射 (JSON)",
    "wf.panel.output_map": "输出映射 (JSON)",
    "wf.panel.expression": "条件表达式",
    "wf.panel.field": "判断字段",
    "wf.panel.routes": "路由规则 (JSON)",
    "wf.panel.route_hint": "路由值填入对应的目标节点 ID（可在画布上查看节点 ID）",
    "wf.panel.expression_hint": "示例: score > 80  status == \"approved\"  amount >= 10000",
    "wf.panel.click_hint": "点击画布中的节点查看属性",
    "wf.empty.desc": "暂无流程，点击\"新建流程\"开始",
    "wf.toast.created": "流程已创建",
    "wf.toast.saved": "保存成功",
    "wf.toast.published": "已发布",
    "wf.test.title": "流程测试",
    "wf.test.running": "模拟执行中...",
    "wf.test.workflow": "流程",
    "wf.test.nodes": "节点",
    "wf.test.edges": "连线",
    "wf.test.node_type.start": "开始",
    "wf.test.node_type.end": "结束",
    "wf.test.node_type.human_task": "人工任务",
    "wf.test.node_type.gateway": "条件网关",
    "wf.test.node_type.agent": "Agent节点",
    "wf.agent.coordinator": "协调者 (coordinator)",
    "wf.agent.supplier_auditor": "供应商审核 (supplier_auditor)",
    "wf.agent.data_analyst": "数据分析 (data_analyst)",
    "wf.panel.id": "ID",
    "wf.panel.type": "Type",
    // ── 知识工作台 ──
    "kb.sidebar.title": "闭环功能分区",
    "kb.sidebar.ready": "完美闭环就绪",
    "kb.sidebar.desc": "集成、本体、安全中心的数据经由此处融合计算，向 Copilot 提供高精度知识驱动。",
    "kb.tab.architecture": "研究方案 / 闭环设计",
    "kb.tab.sync": "元数据集成同步",
    "kb.tab.lineage": "血缘解析与级联影响",
    "kb.tab.ontology": "语义本体对齐映射",
    "kb.tab.index": "知识向量索引构建",
    "kb.tab.rag": "知识检索与 RAG 模拟",
    "kb.tab.graph_sync": "图谱同步",
    "kb.tab.graph_explore": "图谱探索",
    "kb.sync.title": "多模态联邦元数据集成中心",
    "kb.sync.syncAll": "一键全站元数据同步",
    "kb.sync.syncing": "联邦网格抓取中...",
    "kb.sync.assetsTitle": "三大工作台元数据同步列表",
    "kb.sync.assetName": "资产名称",
    "kb.sync.assetSource": "资产来源",
    "kb.sync.metaType": "元数据类型",
    "kb.sync.synced": "最新已对齐",
    "kb.sync.pending": "未同步",
    "kb.sync.outdated": "更迭更新",
    "kb.sync.pull": "拉取同步",
    "kb.lineage.title": "元数据血缘解析器与下游影响分析",
    "kb.lineage.analyzing": "递归推导下游拓扑链条中...",
    "kb.ontology.title": "语义本体与物理宽表对齐管理器",
    "kb.ontology.newEntity": "新建",
    "kb.ontology.exportBtn": "导出 RAG 先验知识元数据包",
    "kb.ontology.saveMapping": "应用并保存强对齐契约",
    "kb.ontology.addMapping": "添加属性映射",
    "kb.index.title": "联邦知识库切块向量化索引引擎",
    "kb.index.chunkConfig": "向量分片参数配置",
    "kb.index.syncBtn": "构建闭环元数据向量库",
    "kb.rag.title": "联邦知识库检索与推理仿真沙箱",
    "kb.rag.searchBtn": "开始检索并模拟推理",
    "kb.rag.retrieving": "向量对齐与元数据检索中...",
    "kb.rag.results": "向量相关度检索结果",
    "kb.rag.promptTitle": "融合生成的提示词",
    "kb.rag.outputTitle": "合规输出",
    "kb.common.close": "关闭",

    // Data Workbench
    "dw.sidebar.title": "集成工作区",
    "dw.tab.guide": "顶层策划：四工具融入五环节",
    "dw.tab.connections": "数据源与物理连接",
    "dw.tab.syncs": "物理数据同步任务",
    "dw.tab.pipelines": "数据转换与 Pipeline",
    "dw.tab.health": "数据质量健康检测",
    "dw.tab.lineage": "全链路数据血缘地图",
    "dw.sidebar.stats": "物理数据监控仪表",
    "dw.sidebar.connections": "外部数据接口",
    "dw.sidebar.syncs": "流批同步管道",
    "dw.sidebar.objects": "已融合对象数",
    "dw.txt.004669": "仅手动触发 (Manual)",
    "dw.txt.01b9b1": "已注入 PB 函数:",
    "dw.txt.033f47": "经推演，本轮开启内存 GC 缓冲区复用与 Web Worker 多线程并行分流后，单机 Hash Map JOIN 效率提升约",
    "dw.txt.03c868": "回收规范:",
    "dw.txt.083142": "🚀 物理引擎:",
    "dw.txt.0d63d3": "HTTP API 网关",
    "dw.txt.0d7003": "架构规划细则 (Implementation Architecture)",
    "dw.txt.0f541b": "全链路数据血缘地图",
    "dw.txt.102168": "数据源与物理连接",
    "dw.txt.1169ed": "用户主凭据 (User ID)",
    "dw.txt.118029": "常驻内存 (RAM Footprint) 上限控制",
    "dw.txt.11add3": "请选择一个物理数据同步任务查看详情",
    "dw.txt.11cefc": "物理数据同步任务",
    "dw.txt.12f07f": "，多维统计聚合算子将直接由本地 BE 分区列索引承载，彻底避免物理 Shuffle 带来的宽带阻塞瓶颈！",
    "dw.txt.12f1d0": "质检规则",
    "dw.txt.153eeb": "SQL 过滤条件:",
    "dw.txt.15e5bb": "物理网络端点",
    "dw.txt.165c7b": "最近连接校验时间",
    "dw.txt.16e578": "服务器 Host",
    "dw.txt.1988fc": "流批同步管道:",
    "dw.txt.1ad16f": "ECOS 分支控制 (Git Branch)",
    "dw.txt.1b23b5": "数据质量健康检测",
    "dw.txt.1e7bf5": "注入 PB 表达式算子",
    "dw.txt.2063a2": "限定判定阈值 (Threshold)",
    "dw.txt.226b09": "类型",
    "dw.txt.26079a": "物理数据湖 Ingress 连接器调试面板",
    "dw.txt.26a4e8": "请选择一个清洗逻辑管道",
    "dw.txt.27ae19": "预览并一键导出方案说明书",
    "dw.txt.282170": "请选择一个物理数据源查看详情",
    "dw.txt.2b6bc0": "操作",
    "dw.txt.2ce9e0": "当前物理数据源连接受阻或未注册可用数据表目录。",
    "dw.txt.2d4ed7": "240ms (优化前) &rarr;",
    "dw.txt.2fa8de": "一、ECOS 核心管道构建四大开发工具",
    "dw.txt.30609b": "180,000 rps (优化后)",
    "dw.txt.30f7dd": "连接",
    "dw.txt.310118": "Colocate 对齐激活",
    "dw.txt.311324": "Aviation Control 运维邮箱",
    "dw.txt.332103": "新建外界物理数据源连接",
    "dw.txt.3423fb": "经推演，本轮开启所有 Apache Doris 分布式列式优化后，大表 JOIN 查询延迟缩短约",
    "dw.txt.34a4de": "当前节点输出 Schema",
    "dw.txt.384142": "，杜绝了由于主线程密集运算带来的任何丢帧卡顿情况！",
    "dw.txt.39cb73": "二、官方标准数据管道构建五步法 (可交互演练环境)",
    "dw.txt.3a0fd4": "⚡ 计算引擎与调优",
    "dw.txt.3a7896": "下游落湖 (Silver)",
    "dw.txt.3a8093": "功能描述与规范定义",
    "dw.txt.3bdd08": "描述",
    "dw.txt.3cd968": "API 端点网关",
    "dw.txt.3dfa9c": "算法模型:",
    "dw.txt.3f6461": "📂 ECOS 生产级底层代码参考",
    "dw.txt.3fea7c": "状态",
    "dw.txt.4016cf": "网关 Port",
    "dw.txt.419d9f": "物理数据监控仪表",
    "dw.txt.42bc1b": "对方可读取数据表/目录列表",
    "dw.txt.445bdd": "24 次/天",
    "dw.txt.44a230": "已融合对象数:",
    "dw.txt.44d70b": "42ms (优化后)",
    "dw.txt.44e8b3": "请先修改配置或完成物理连接探测握手。",
    "dw.txt.48e387": "🟢 核心优势:",
    "dw.txt.496a4b": "最近上报版本标签",
    "dw.txt.4aa8c3": "联动警报接收路由 (Webhooks)",
    "dw.txt.4c96fe": "物理源数据表/文件夹",
    "dw.txt.52d7f4": "监控目标落湖表",
    "dw.txt.53ace4": "已启用",
    "dw.txt.558887": "Doris BE 物理查询及多维扫描延迟",
    "dw.txt.578202": "0 MB (Colocate 本地化)",
    "dw.txt.58314a": "物理源名称 (Connection Name)",
    "dw.txt.58d7c8": "集成工作区",
    "dw.txt.5ac0cc": "对方数据表/物理目录",
    "dw.txt.5c5633": "开启并行分流",
    "dw.txt.5c9d54": "列数:",
    "dw.txt.5da13f": "所有物理同步/提取任务",
    "dw.txt.5e099e": "时效时限违约事件",
    "dw.txt.5fa09f": "微批流处理每 30s 注入 (Micro-batch)",
    "dw.txt.5fcc68": "所有规则校验",
    "dw.txt.64d3b2": "所有外界物理数据源",
    "dw.txt.64d859": "行数 (Est):",
    "dw.txt.65779d": "物理数据湖源、ETL 清洗及数据血缘的一体化管理中心",
    "dw.txt.6651d2": "最近执行统计报告",
    "dw.txt.679c15": "首选数据引擎",
    "dw.txt.67d95e": "450ms (优化前) &rarr;",
    "dw.txt.6974b2": "同步计算吞吐耗时",
    "dw.txt.69ef1e": "每小时 05 分定时计算 (Hourly)",
    "dw.txt.6dd76a": "监控 ECOS 在库数据集的质量漂移，当违背阈值时触发报警或执行阻断。",
    "dw.txt.6fbcb9": "转换前 (Before Source Ingress)",
    "dw.txt.70edaa": "算子规则配置 (Operator Editor)",
    "dw.txt.721755": "检测触发阈值与报警边界",
    "dw.txt.72717e": "多核调度:",
    "dw.txt.72a256": "物理堆内存空间占用：严格控制在 12 MB 独占",
    "dw.txt.74eeaf": "物理数据源",
    "dw.txt.79a539": "MV 声明:",
    "dw.txt.7adcd8": "连接端口 (Port)",
    "dw.txt.7de8db": "数据工作台 (Data Workbench)",
    "dw.txt.8018fb": "垃圾回收 (GC GC Pause) 卡顿时间",
    "dw.txt.80aaef": "高频 Cron 计划",
    "dw.txt.811feb": "最少行数警示水位",
    "dw.txt.813a1c": "运行调度频度",
    "dw.txt.8240a1": "飞书监控报警卡片推送",
    "dw.txt.8244ee": "同步算法规范",
    "dw.txt.824885": "同步模式",
    "dw.txt.831c7d": "增量提取 (Incremental)",
    "dw.txt.84bea7": "Doris 列式存储物理空间压缩率",
    "dw.txt.88e804": "⚙️ 核心支撑组件",
    "dw.txt.8addbe": "秒级索引加速",
    "dw.txt.8be220": "时效指标监控 (SLA Freshness)",
    "dw.txt.911247": "外界物理源 (Ingress Source)",
    "dw.txt.91ab83": "新建数据质量健康检查",
    "dw.txt.952c30": "调度触发频率 (Frequency)",
    "dw.txt.957599": "选择计算引擎",
    "dw.txt.97a690": "末尾追加 (Append)",
    "dw.txt.9b600a": "正在运行物理运算模拟...",
    "dw.txt.9caecd": "字段",
    "dw.txt.9df05c": "📊 数据生命周期流转",
    "dw.txt.9f1c94": "840 MB (优化前) &rarr;",
    "dw.txt.a001a2": "更新时间",
    "dw.txt.a35326": "物理作业触发频率",
    "dw.txt.a7e407": "立即启动提取同步 (Run Ingest)",
    "dw.txt.aaf147": "主机/端点主机 (Host / URL)",
    "dw.txt.ac4313": "配属等级:",
    "dw.txt.af2c4a": "聚合粒度:",
    "dw.txt.b22078": "12,000 rps (优化前) &rarr;",
    "dw.txt.b316a5": "检测规则分类",
    "dw.txt.b35137": "当前分支:",
    "dw.txt.b36472": "作业稳定性大盘 (Stability Panel)",
    "dw.txt.b478e4": "🛠️ 管道构建与算子",
    "dw.txt.ba49ba": "拉取同步总行数",
    "dw.txt.bb0cb7": "单次平准计算延迟",
    "dw.txt.bb4a1b": "重试及退避间隔 (Retry backoff)",
    "dw.txt.bbedcc": "运行计划 & 时间周期",
    "dw.txt.bca5fe": "数据总行数校验 (Min Rows)",
    "dw.txt.bdfb20": "一键复制全套方案",
    "dw.txt.c2750e": "最大计算阻断超时 (Max Duration)",
    "dw.txt.c40508": "编译并运行管道",
    "dw.txt.c4a9c9": "表结构字段一致性校验 (Schema)",
    "dw.txt.c56266": "顶层策划：四工具融入五环节",
    "dw.txt.c59de0": "O(1) 匹配极速",
    "dw.txt.c5dda0": "外界系统集成接口 (APIs / Sources)",
    "dw.txt.c6f0b6": "数据湖目的物理表 (Raw Dataset ID)",
    "dw.txt.c8767b": "单步执行质检 rules",
    "dw.txt.ca6183": "最近一次任务时间",
    "dw.txt.cb8b5d": "平均冷启动消耗时间",
    "dw.txt.cdb140": "列字段 (Column)",
    "dw.txt.ce3ee2": "计算节点:",
    "dw.txt.d04d82": "请选择一个数据质检健康规则",
    "dw.txt.d086dc": "最大可承受空值比例 (Max Null %)",
    "dw.txt.d28316": "钉钉/企业微信工作流机器人",
    "dw.txt.d30131": "📅 SLA 调度与监控",
    "dw.txt.d32eec": "任务说明 (Task Name)",
    "dw.txt.d43c1e": "Doris 分布式节点跨节点 Shuffle 交换",
    "dw.txt.d4e181": "每小时定时",
    "dw.txt.d5588c": "全量快照 (Snapshot)",
    "dw.txt.d6aaff": "配置项:",
    "dw.txt.d7ec2d": "名称",
    "dw.txt.d85c7b": "提取任务",
    "dw.txt.d8a8a4": "复制示例",
    "dw.txt.dbe3d6": "ECOS 核心开发工具",
    "dw.txt.dd7543": "V8 内存清洗吞吐率 (Throughput)",
    "dw.txt.de8bec": "🛠️ 支撑语言:",
    "dw.txt.dec92b": "集成协议与驱动",
    "dw.txt.e23d93": "每日凌晨 02:00 (Daily batch)",
    "dw.txt.e3e567": "⚠️ 调度延滞时效性预警",
    "dw.txt.e442a8": "SLA 时效阻塞界限 (分钟)",
    "dw.txt.e4f186": "🔴 开发避坑:",
    "dw.txt.e54c87": "0 次违约 (Green)",
    "dw.txt.e6fdc9": "MPP 列存优化：节省存储空间 82%",
    "dw.txt.e77c42": "日均作业实例数",
    "dw.txt.e9bc2c": "每日定时",
    "dw.txt.ead4a7": "🚨 物理脏数据比率阻断阀值",
    "dw.txt.eb9003": "目标 S3 存储桶",
    "dw.txt.ec7002": "缩放: 100%",
    "dw.txt.eeb061": "DDL 语法项:",
    "dw.txt.eed3c7": "同步源及目标存储",
    "dw.txt.f0eff8": "格式:",
    "dw.txt.f17556": "S3 落点存储桶",
    "dw.txt.f274bd": "外界物理系统名称",
    "dw.txt.f2e8f6": "检测规则名称 (Rule Name)",
    "dw.txt.f4deb5": "ECOS 官方反模式警示 (Anti-Pattern Warning)",
    "dw.txt.f58b36": "2.45 秒",
    "dw.txt.f636a1": "测试物理握手 (Test Ingress)",
    "dw.txt.f6ebf8": "已激活",
    "dw.txt.f75e4f": "比率 &gt; 1%",
    "dw.txt.f786e8": "用户认证账号 (Username / IAM)",
    "dw.txt.f7d9ac": "外部数据接口:",
    "dw.txt.f80f8b": "关联条件 (Keys):",
    "dw.txt.fb1d84": "关键字段空值控制 (Null Check)",
    "dw.txt.fdcb6f": "数据转换与 Pipeline",
    "dw.txt.fde125": "8ms (优化后)",
    "dw.txt.fe3609": "数据库/源类别 (Type)",

    // Ontology
    "ontology.confirm_delete_element": "确认删除此本体元素吗？该操作不可撤销。",
    "ontology.cannot_delete_pk": "无法删除主键属性！",
    "ontology.confirm_delete_domain": "确定要删除业务划分域「{name}」吗？关联的实体将变更为未分类。",
    "dw.txt.ff8464": "新建物理数据拉取同步任务",
  },
  en: {
    // Brand
    "brand.title": "C2EOS Cognitive Kernel",
    "brand.kernel": "Cognitive Kernel v15.1",

    // Sidebar navigation groups
    "nav.group.primary": "Primary Workspace",
    "nav.group.data_platform": "Data Platform",
    "nav.group.knowledge": "Knowledge Layer",
    "nav.group.aip": "AIP Agent Operating System",
    "nav.group.security": "Security & Governance",
    "nav.group.marketplace": "Data Marketplace",

    // Sidebar navigation items
    "nav.item.mission_control": "Mission Control",
    "nav.item.mission_control.desc": "ECOS Strategic Dashboard",
    "nav.item.catalog": "Data Catalog",
    "nav.item.catalog.desc": "Assets metadata list",
    "nav.item.explorer": "Datasets Explorer",
    "nav.item.explorer.desc": "Schema, preview, quality files",
    "nav.item.lineage": "Data Lineage",
    "nav.item.lineage.desc": "End-to-end telemetry graph",
    "nav.item.pipeline": "Pipeline Builder",
    "nav.item.pipeline.desc": "DAG code & node designer",
    "nav.item.workbook": "Code Workbook",
    "nav.item.workbook.desc": "Write Python & SQL notebooks, plot analysis graphs",
    "nav.item.ontology": "Ontology Manager",
    "nav.item.ontology.desc": "Entity & Relationship model list",
    "nav.item.ops_apps": "Operational Applications",
    "nav.item.ops_apps.desc": "Action applications and execution dashboards",
    "nav.item.monitor": "Monitoring Center",
    "nav.item.monitor.desc": "Global health index and data audit radars",
    "nav.item.agent": "Agent Studio",
    "nav.item.agent.desc": "Specialist agents, prompt blueprints",
    "nav.item.security": "RBAC & Audit Logs",
    "nav.item.security.desc": "Compliance locks, signed index list",

    // Sidebar footer
    "sidebar.status": "System Status",
    "sidebar.status.optimal": "OPTIMAL",
    "sidebar.spark_jobs": "Active Spark DAGs",
    "sidebar.spark_jobs.active": "Active",
    "sidebar.latency": "COGNITIVE LATENCY",

    // Topbar
    "topbar.admin": "Administrator",
    "topbar.role": "Commander Level 4",
    "topbar.palette": "Command palette...",
    "topbar.c2eos": "C2EOS",
    "topbar.user.settings": "Configuration Settings",
    "topbar.user.email": "Secure Email Address",
    "topbar.user.clearance": "Access Clearance Level",
    "topbar.user.workstation": "Linked Safe Workstation",
    "topbar.user.auditlevel": "Dual-Write Audit Mode",
    "topbar.user.auditlevel.full": "Full Cryptographic ABAC Chain Signature",
    "topbar.user.auditlevel.standard": "Standard Ledger Audit Records Only",
    "topbar.user.sandbox": "Mandatory Sandbox Verification for Actions",
    "topbar.user.reset": "Wipe Local Cache",
    "topbar.user.reset.success": "Workspace parameters and UI state logs fully flushed!",
    "topbar.user.save": "Verify & Save Profile",
    "topbar.user.save.success": "Local config stored securely. Connection hot-reloaded successfully!",

    // Breadcrumbs
    "bc.cognitive_core": "Cognitive Core",
    "bc.mission_control": "Mission Control",
    "bc.data_platform": "Data Platform",
    "bc.data_catalog": "Data Catalog",
    "bc.datasets_explorer": "Datasets Explorer",
    "bc.lineage_graph": "Lineage Graph",
    "bc.pipeline_dag": "Pipeline DAG Designer",
    "bc.knowledge_layer": "Knowledge Layer",
    "bc.ontology_manager": "Ontology Manager",
    "bc.cognitive_layer": "Cognitive Layer",
    "bc.aip_agent_studio": "AIP Agent Studio",
    "bc.security_audit": "Security & Audit",
    "bc.access_policies": "Access Policies",
    "bc.system": "System",
    "bc.workspace": "Workspace",
    "theme.label": "Theme Style",
    "theme.slate-light": "Slate Light (Clear)",
    "theme.deep-space": "Deep Space (Dark)",
    "theme.cyber-terminal": "Cyber Terminal (Green)",
    "theme.royal-purple": "Royal Purple (Amethyst)",

    // Pages common / general
    "btn.close": "Close",
    "btn.cancel": "Cancel",
    "btn.submit": "Submit Action Command",

    // 1. CognitiveOperatingSystem (Mission Control)
    "cos.title": "C2EOS Enterprise Cognitive Shell",
    "cos.desc": "Observe complex root causes, run simulated world-model sandbox forecasts, and discover optimal multi-objective Pareto Frontier guidelines.",
    "cos.simulating": "ECOS SIMULATING SCENARIOS...",
    "cos.btn.simulate": "Simulate Current Sandbox Forecast",
    "cos.kpi.rev": "Maximize Aggregate Revenue",
    "cos.kpi.rev.status": "At Risk",
    "cos.kpi.rev.target": "Target Limit: >$1.1B",
    "cos.kpi.delay": "Minimize Factory Delays",
    "cos.kpi.delay.status": "Behind",
    "cos.kpi.delay.target": "Target Limit: <2.0%",
    "cos.kpi.safety": "HSE Safe Zero Incidents",
    "cos.kpi.safety.status": "Green Optimal",
    "cos.kpi.safety.target": "Zero-risk operational ceiling",
    "cos.kpi.safety.val": "Level 0 Issues",
    "cos.graph.title": "C2EOS Enterprise Cause Graph Layout",
    "cos.graph.btn.pareto": "Determine Pareto Frontier guidelines",
    "cos.graph.pareto.title": "ECOS Optimization Pareto Frontier Multi-goal solver",
    "cos.graph.node.inspect": "Root-cause diagnostics analysis",
    "cos.graph.node.weight": "Direct influence weight:",
    "cos.graph.node.cause": "Incident root causes:",
    "cos.graph.node.effect": "Trigger downstream cascades:",
    "cos.graph.node.explain": "Analytical advice summary:",
    "cos.sim.sandbox": "Enterprise decision twin simulator",
    "cos.sim.scenario": "Choose simulation scenario run:",
    "cos.sim.outage": "Planned maintenance outages hours (hrs):",
    "cos.sim.extra": "Extra critical shifts weekly capacity frequency:",
    "cos.sim.output": "Decision run sandbox logs console output:",
    "cos.sim.idle": "No active job runs. Click Simulation to trigger ECOS optimization logs.",

    // 2. DataCatalog (Data Catalog)
    "catalog.title": "Enterprise core metadata Assets directory",
    "catalog.desc": "Retrieve, explore, and access governed physical datasets metadata registered within the ECOS active repository catalog.",
    "catalog.placeholder": "Filter assets metadata by labels, tags, schema descriptions, namespaces database structures...",
    "catalog.btn.register": "Register Unified Physical Table (DDL/JDBC Connect)",
    "catalog.meta.summary": "Governed catalog summaries",
    "catalog.meta.assets": "Governed Data Assets",
    "catalog.col.asset": "Data physical assets name",
    "catalog.col.type": "Storage formats",
    "catalog.col.quality": "Physical Quality",
    "catalog.col.domain": "Enterprise Domain",
    "catalog.col.rows": "Logical entries size",
    "catalog.col.updated": "Computed metadata sync",
    "catalog.btn.explore": "Inspect Details Table",

    // 3. DatasetExplorer
    "db.back": "Back to governed metadata catalog",
    "db.desc": "Inspect data structural patterns, look up sampling entries, and configure active quality gates.",
    "db.tab.schema": "Table Schema Blueprint",
    "db.tab.data": "Physical data sampler view",
    "db.tab.rules": "Quality validation rules",
    "db.tab.lineage": "Interactive data flow lineage",
    "db.quality_rules": "Deploy verification rules guidelines",
    "db.columns": "Columns",
    "db.rows": "Rows",
    "db.size": "Size on disk",
    "db.col.field": "Physical field",
    "db.col.type": "Physical type",
    "db.col.quality": "Integrity score",
    "db.col.desc": "Metadata semantics glossary",
    "db.rules.rule": "Verification rule title",
    "db.rules.type": "Compliance standard class",
    "db.rules.status": "Gate outcome status",
    "db.lineage.info": "Shows full lineage tracking downstream dependencies and upstream generators.",

    // 4. PipelineBuilder
    "pb.title": "Pipeline Builder Workstations",
    "pb.desc": "Visually assemble, compile and execute server-authoritative Spark jobs as modular DAG nodes.",
    "pb.compiling": "SPARK EXECUTOR KERNELS RUNNING...",
    "pb.btn.compile": "Compile & Execute DAG Flow",
    "pb.editor.title": "Visual Node DAG Flow Designer",
    "pb.editor.authoritative": "Workspace authoritative",
    "pb.sidebar.title": "DAG Node Configurator",
    "pb.sidebar.node_type": "Node Operator Type",
    "pb.sidebar.sql": "Vite Aggregate function (SQL)",
    "pb.sidebar.namespace": "Target Namespace File",
    "pb.sidebar.empty": "Select a DAG Node block to inspect spark job properties.",

    // 5. OntologyExplorer
    "ont.title": "Ontology Manager & Action Engine",
    "ont.desc": "Map databases to semantic objects, establish strict relation graphs, and execute compliant operations.",
    "ont.loading": "Loading...",
    "ont.load_error": "Ontology data load failed",
    "ont.btn.define": "Define Object Class (YAML DSL)",
    "ont.sidebar.title": "Ontology Objects",
    "ont.workbench.title": "Design State Ontology Object Blueprint",
    "ont.workbench.props": "Property Properties list",
    "ont.workbench.rel": "Relationship bounds",
    "ont.workbench.required": "Required",
    "ont.workbench.constraint": "Constraint: Referential Integrity checking is enforced globally at runtime by the ECOS kernel compiler.",
    "ont.workbench.actions": "Enforced Ontology Actions",
    "ont.workbench.form_active": "Interactive Command Form:",
    "ont.workbench.high_impact": "High Impact",
    "ont.workbench.topo": "Map Topology",
    "ont.workbench.toast_fail": "HIGH IMPACT ACTION SUSPENDED: Draft generated under regulatory workflow rules. Raised pending authorization request in Security Audit.",
    "ont.workbench.toast_success": "Action executed successfully! Dynamic runtime schema logs updated. Audit log registered.",
    "ont.workbench.alert_prompt": "Ontology modeling requires system administrator role. Read design documentation in AGENTS.md.",
    "ont.workbench.submit_btn": "Submit Action Command",

    // 6. AgentStudio
    "agent.title": "AIP Agent Studio Workbench",
    "agent.desc": "Decompose workflow goals into modular multi-agent planning frameworks using prompt sandboxes, specialist tool Registries, and trace evaluators.",
    "agent.btn.eval": "Trigger Forensics Trace Analysis",
    "agent.sidebar.agents": "Specialist Agents",
    "agent.sidebar.tools": "Specialist Tool registry",
    "agent.sandbox.title": "Developer prompts sandbox",
    "agent.sandbox.filepath": "File path:",
    "agent.sandbox.version": "Prompt Version:",
    "agent.trace.under": "Enforced via OpenTelemetry API standards",
    "agent.trace.idle": "Observer status: IDLE. Press Trigger forensics to trace Agent Planning steps.",
    "agent.gauges.title": "Agent Economics metrics",
    "agent.gauges.success": "Consensus Success rate",
    "agent.gauges.tokens": "Cumulative Tokens",
    "agent.gauges.dollars": "Accrued Model Cost",
    "agent.gauges.tools_count": "Tools Invocations Count",
    "agent.gauges.warn": "Token Cap quotas",
    "agent.gauges.warn_desc": "Accrued token costs map against Central Enterprise thresholds rules defined under ECOS.",

    // 7. SecurityAudit
    "sec.title": "Compliance Shield & Non-repudiated audits logs",
    "sec.desc": "Enforce advanced role-based row & column filters to isolate sensitive fields, backed by secure cryptographic operations registers.",
    "sec.btn.add": "Draft secure policy configuration lock",
    "sec.meta.active": "Quotas Shield Active",
    "sec.meta.event": "Hashed Audit logs blocks",
    "sec.meta.rule": "Access filters rules set",
    "sec.tb.audit_title": "Cryptographically-chained Audit Trails Log Register",
    "sec.tb.col.time": "Time log (UTC)",
    "sec.tb.col.actor": "Actor credentials",
    "sec.tb.col.action": "Enforced operation",
    "sec.tb.col.target": "Bound Object Class",
    "sec.tb.col.details": "Security verification payload signature",
    "sec.tb.col.status": "Kernel outcome",
    "sec.tb.status.success": "Signature Verified (Granted)",
    "sec.tb.status.pending": "Chamber approval pending",
    "sec.rbac.title": "Role-Based Row & Column level security policies (RBAC)",
    "sec.rbac.col.target": "Class context properties target",
    "sec.rbac.col.rule": "Quora Access restrictions rule",

    // New keys for DatasetExplorer detail views
    "db.stats.title": "Namespace Statistics",
    "db.stats.rows": "Total Row Records",
    "db.stats.cols": "Column Fields",
    "db.stats.size": "Logical Size",
    "db.stats.quality": "Quality Level",
    "db.history.title": "Dataset Revision History",
    "db.history.empty": "No historical records audited for this target namespace.",
    "db.meta.title": "System Metadata",
    "db.meta.domain": "Domain Directory",
    "db.meta.tags": "System Tags",
    "db.permissions.title": "Access Control List",
    "db.permissions.owner": "Administrative Owners",
    "db.permissions.editor": "Authorized Editors",
    "db.permissions.viewer": "Default Viewers",
    "db.fields.title": "Data Namespace Fields",
    "db.fields.col_field": "Column Field",
    "db.fields.col_type": "DataType",
    "db.fields.col_null": "Nullable",
    "db.fields.col_quality": "Quality Score",
    "db.inspector.title": "Namespace Inspector",
    "db.inspector.type": "DataType Typecast",
    "db.inspector.nullability": "Nullability Contract",
    "db.inspector.null_yes": "NULL Permitted (Optional)",
    "db.inspector.null_no": "NOT NULL Enforced (Required Key)",
    "db.inspector.semantics": "Description / Semantics",
    "db.inspector.empty_semantics": "No description registered in schema catalog.",
    "db.inspector.quality": "Field Quality Score",
    "db.inspector.quality_desc": "Verified via continuous regression checks. Zero null pointer violations or orphan targets detected.",
    "db.inspector.empty": "Select a variable column to inspect semantic properties.",
    "db.inspector.policy": "Enforced by Ontology layer policies",
    "db.preview.title": "Transactional Preview (Rows 1 to limit rows limit)",
    "db.preview.desc": "Enforced schema limits, read and show first 100 rows",
    "db.preview.sql": "SQL preview equivalent: ",
    "db.quality.active_rules": "Active Data Quality Check rules",
    "db.quality.method": "Method Type: ",
    "db.quality.health_grade": "Overall Health Grade",
    "db.quality.certified": "This dataset is certified for executive decisions and model training because its reference index has passed all primary null, range and deduplication tests.",
    "db.quality.caution": "Caution: Thermal sensors flagged critical spike limits. Quality checks detected 3 anomaly outliers within regional machinery indexes during daily pipeline ingestion loops.",
    "db.lineage.centered": "Interactive local lineage graph centered on: ",

    // New keys for SecurityAudit detail views
    "sec.ledger.title": "Immutable audit ledger logs (Cryptographically signed)",
    "sec.ledger.subtitle": "Live Telemetry feed",
    "sec.ledger.voucher": "Voucher Code: ",
    "sec.ledger.committed": "Committed",
    "sec.ledger.pending": "Pending Signoff",
    "sec.directives.title": "Security Directives",
    "sec.directives.subtitle": "Attribute Authorization Rules",
    "sec.directives.desc": "Enforces precise dataset limits at compile stage. Columns and partitions are filtered dynamically by employee role constraints.",
    "sec.directives.policy_label": " policy",
    "sec.directives.scope_class": " Scope Class",
    "sec.directives.condition": "Condition: ",
    "sec.directives.unlimited": "Unlimited Access",
    "sec.bounds.title": "Compliant bounds",
    "sec.bounds.desc": "ECOS metadata restricts database joins, ensuring compliance with Sox, GDPR and workplace protection laws dynamically.",

    // New keys for OntologyExplorer details
    "ont.blueprint.title": "Design State Ontology Object Blueprint",
    "ont.blueprint.object_suffix": " Object Class",
    "ont.properties.required": "Required",
    "ont.actions.title": "Enforced Ontology Actions",
    "ont.form.title": "Interactive Command Form: ",
    "ont.form.close": "Close (X)",
    "ont.form.cancel": "Cancel",
    "ont.form.placeholder_true": "True (Enabled)",
    "ont.form.placeholder_false": "False (Disabled)",
    "ontology_designer.confirm_delete": "Delete the entity and its properties/relationships. Confirm?",
    "object_explorer.confirm_delete": "Confirm delete this object?",

    // GlossaryManager
    "glossary.title": "Glossary",
    "glossary.unit": "terms",
    "glossary.all": "All",
    "glossary.search_placeholder": "Search terms...",
    "glossary.new_term": "New Term",
    "glossary.loading": "Loading...",
    "glossary.no_match": "No match for",
    "glossary.empty": "No terms yet. Click \"+ New Term\" to start.",
    "glossary.empty_hint": "Click \"+ New Term\" to start, or select a term from the left.",
    "glossary.term_detail": "Term Detail",
    "glossary.edit": "Edit",
    "glossary.delete": "Delete",
    "glossary.save": "Save",
    "glossary.cancel": "Cancel",
    "glossary.actions": "Actions",
    "glossary.delete_confirm_title": "Confirm Delete",
    "glossary.delete_confirm_msg": "Are you sure you want to delete \"{name}\"? This cannot be undone.",
    "glossary.field.name": "Term Name",
    "glossary.field.name_placeholder": "e.g. Data Lineage",
    "glossary.field.domain": "Domain",
    "glossary.field.domain_placeholder": "Select domain",
    "glossary.field.definition": "Definition",
    "glossary.field.definition_placeholder": "Describe the term...",
    "glossary.field.status": "Current Status",
    "glossary.status.draft": "Draft",
    "glossary.status.review": "Review",
    "glossary.status.published": "Published",
    "glossary.transition.submit_review": "Submit for Review",
    "glossary.transition.publish": "Publish",
    "glossary.transition.deprecate": "Deprecate",
    "glossary.toast.load_failed": "Load failed",
    "glossary.toast.name_required": "Term name is required",
    "glossary.toast.created": "Term created",
    "glossary.toast.updated": "Term updated",
    "glossary.toast.save_failed": "Save failed",
    "glossary.toast.status_changed": "Status changed to",
    "glossary.toast.status_failed": "Status change failed",
    "glossary.toast.deleted": "deleted",
    "glossary.toast.delete_failed": "Delete failed",

    // 8. Code Workbook keys
    "wb.title": "Code Workbook Analytical Workbench",
    "wb.desc": "Physical and logical analysis. Python, SQL multi-block real-time simulation and reactive notebook computation.",
    "wb.sidebar.header": "Data Models",
    "wb.active.dfs": "Loaded DataFrames",
    "wb.active.dfs.rows": "rows",
    "wb.active.dfs.cols": "cols",
    "wb.stream.mappings": "Stream Mappings",
    "wb.runtime": "Workbook Runtime",
    "wb.memory": "Memory allocated: 32GB (Optimal)",
    "wb.run.all": "Run Entire Workbook Workflow (Spark)",
    "wb.active.cell": "Cell",
    "wb.active.idle": "Unmodified execution",
    "wb.active.success": "SUCCESS (1.2s)",
    "wb.active.running": "COMPILING SPARK EXEC...",
    "wb.active.outputs": "Explore Outputs",
    "wb.active.outputs.placeholder": "Run cell to execute spark visualization",

    // 9. Operational Applications keys
    "ops.title": "C2EOS Operational Actions Workspace",
    "ops.desc": "Dually aligned semantic ontology interactive center with Specialist AI. All operations are permanently stored inside immutable ledgers.",
    "ops.tab.crm": "Customer Risk",
    "ops.tab.maint": "Operations Scheduling",
    "ops.tab.fin": "Escrow Billing Audit",
    "ops.crm.header": "Integrated Customer Credit Desk (Slate)",
    "ops.crm.select": "Select Target Customer Object Class",
    "ops.crm.status": "Operating Status",
    "ops.crm.revenue": "Annual Operating Revenue",
    "ops.crm.region": "Strategic Operating Cluster",
    "ops.crm.churn": "Churn Risk Metric Score",
    "ops.crm.control.credit": "Credit Limits Adjustment Allocation",
    "ops.crm.control.credit.btn": "Authorize Adjustment",
    "ops.crm.control.credit.hint": "Compliance rule: Over-allocations exceeding $5M USD trigger supervisor signature check.",
    "ops.crm.control.freeze": "Hazard Safety Intercept Isolations",
    "ops.crm.control.freeze.btn": "Emergency Suspension Switch (Freeze)",
    "ops.crm.control.freeze.hint": "This operation immediately blocks outbound trade and settlement API pipes across child modules.",
    "ops.maint.header": "Machinery Thermal Fault Hot Intervention Terminal (Workshop)",
    "ops.maint.col.id": "Unit Code",
    "ops.maint.col.temp": "Core Temperature",
    "ops.maint.col.status": "Diagnostics Level",
    "ops.maint.col.action": "Command Dispatch",
    "ops.maint.action.btn": "Issue Maintenance Voucher",
    "ops.maint.action.ok": "Normal stable operations",
    "ops.maint.settings": "Voucher Dispatch Attributes",
    "ops.maint.priority": "Repair Service SLA Priority",
    "ops.maint.note": "Dispatcher Directives Commentary",
    "ops.maint.note.placeholder": "Ex: Unit overheat warnings. Dispatch Team Charlie ASAP.",
    "ops.fin.header": "Reconciliation Escrow Approvals Gate (Secure Slate)",
    "ops.fin.warning.title": "Automated reconciliation limit exceeded",
    "ops.fin.warning.desc": "Detected pending ledger items exceeding the self-balanced threshold ($1,500,000.00 USD). Escalated to multi-agent security sandbox for supervisor compliance verification.",
    "ops.fin.detail.id": "Pending Transaction ID:",
    "ops.fin.detail.client": "Consignee Trading Partner:",
    "ops.fin.detail.amount": "Clearance Settlement Sum:",
    "ops.fin.btn.approve": "Dual-Authorize Compliance Release",
    "ops.fin.btn.reject": "Refuse & Escalate Risk Alerts",
    "ops.panel.title": "Semantic Ontology Integration Advantages",
    "ops.panel.p1": "Unlike direct database raw tables, objects are mapped to high-integrity logical Entity classes with rigorous schemas.",
    "ops.panel.p2.title": "Double-write Ledger:",
    "ops.panel.p2.desc": "Every mutation action is checked against active row-level attribute constraints in real time to avoid tampering.",
    "ops.panel.p3.title": "Uniqueness signature:",
    "ops.panel.p3.desc": "Crucial business actions publish cryptographically secure credentials directly to the central Security Logs table.",

    // 10. Monitoring Center keys
    "mon.title": "C2EOS System Operations Monitoring Control Center",
    "mon.desc": "Live physical node hypervisor monitors, Spark batch ingest stats, CDC lags, and data quality check systems.",
    "mon.btn.diag": "Full Telemetry Diagnostics",
    "mon.diag.success": "DIAGNOSTIC_COMPLETED: CDRC MySQL connections verified. Spark streaming DAG nodes linked flawlessly. Dual-Write semantic ontology verification rules successfully completed. 0 vulnerabilities or orphaned records detected.",
    "mon.kpi.cpu": "C2EOS Core CPU Load",
    "mon.kpi.cpu.desc": "16-Cores Allocated VM",
    "mon.kpi.mem": "Memory Allocation",
    "mon.kpi.mem.desc": "Of total 32.0 GB pool",
    "mon.kpi.spark": "Spark Ingest Rates",
    "mon.kpi.spark.desc": "Continuous micro-batch ingest",
    "mon.kpi.db": "DB Socket Connection Health",
    "mon.kpi.db.desc": "Active pool resources: 24/100",
    "mon.chart.title": "Global Spark Streaming Batch Ingest Load & Speeds (Packets/sec)",
    "mon.daemon.title": "Continuous Execution Daemons & Active Spark Drivers",
    "mon.daemon.col.job": "Daemon / Active Jobs",
    "mon.daemon.col.type": "Physical Class",
    "mon.daemon.col.uptime": "Active Duration",
    "mon.daemon.col.count": "Integrity Records Checked",
    "mon.rules.title": "Live Quality Metrics Warning Registry",

    // AgentStudio additions
    "agent.list.title": "Specialist Agents",
    "agent.list.empty": "No agents yet. Click 'Create Agent' to add one.",
    "agent.tools.title": "Specialist Tool Registry",
    "agent.tools.empty": "No tools registered yet.",
    "agent.chat.title": "Agent Chat Console",
    "agent.chat.placeholder": "Ready. Select an agent and type a message to begin.",
    "agent.chat.send": "Send",
    "agent.chat.error": "Agent API Error",
    "agent.trace.title": "Thought Trace",
    "agent.trace.placeholder": "Thought trace will appear here after sending a message.",
    "agent.metrics.title": "Performance Gauges",
    "agent.metrics.subtitle": "Agent Economics Metrics",
    "agent.metrics.successRate": "Success Rate",
    "agent.metrics.latency": "Last Latency",
    "agent.metrics.tokens": "Cumulative Tokens",
    "agent.metrics.toolCalls": "Tool Calls",
    "agent.create.title": "Create New Agent",
    "agent.create.btn": "New Agent",
    "agent.create.name": "Agent Name",
    "agent.create.role": "Role Description",
    "agent.create.goal": "Goal",
    "agent.create.prompt": "System Prompt",
    "agent.create.confirm": "Create Agent",
    "agent.create.roleDefault": "General Agent",
    "agent.create.goalDefault": "Assist with various tasks",
    "agent.backend.title": "Backend Status",
    "agent.backend.desc": "Connected to ECOS Agent Runtime via BFF proxy. Responses include thought traces from the Java backend.",

    // Pipeline Builder
    "pipeline.title": "Pipeline Orchestration",
    "pipeline.desc": "Create and manage DAG data pipelines, orchestrate Spark/Flink/Batch job nodes",
    "pipeline.btn.compile": "Compile & Execute",

    // 11. Workflow Designer
    "wf.title": "Workflow Designer",
    "wf.desc": "Drag-and-drop visual workflow design with embedded Agent nodes",
    "wf.btn.create": "New Workflow",
    "wf.btn.save": "Save",
    "wf.btn.publish": "Publish",
    "wf.btn.test": "Test",
    "wf.btn.back": "Back to List",
    "wf.btn.close": "Close",
    "wf.status.published": "Published",
    "wf.status.draft": "Draft",
    "wf.node_type.start": "Start",
    "wf.node_type.end": "End",
    "wf.node_type.human_task": "Human Task",
    "wf.node_type.agent_node": "Agent Node",
    "wf.node_type.condition_gateway": "Gateway",
    "wf.palette.title": "Node Palette",
    "wf.designer.untitled": "Untitled Workflow",
    "wf.designer.no_name": "Untitled",
    "wf.panel.label": "Node Name",
    "wf.panel.assignee": "Assignee",
    "wf.panel.agent_role": "Agent Role",
    "wf.panel.tools": "Tools",
    "wf.panel.input_map": "Input Mapping (JSON)",
    "wf.panel.output_map": "Output Mapping (JSON)",
    "wf.panel.expression": "Condition Expression",
    "wf.panel.field": "Field",
    "wf.panel.routes": "Routing Rules (JSON)",
    "wf.panel.route_hint": "Fill in target node IDs matching the routing values (check node IDs on canvas)",
    "wf.panel.expression_hint": "Examples: score > 80  status == \"approved\"  amount >= 10000",
    "wf.panel.click_hint": "Click a node on the canvas to inspect properties",
    "wf.empty.desc": "No workflows yet, click \"New Workflow\" to begin",
    "wf.toast.created": "Workflow created",
    "wf.toast.saved": "Saved",
    "wf.toast.published": "Published",
    "wf.test.title": "Workflow Test",
    "wf.test.running": "Simulating...",
    "wf.test.workflow": "Workflow",
    "wf.test.nodes": "Nodes",
    "wf.test.edges": "Edges",
    "wf.test.node_type.start": "Start",
    "wf.test.node_type.end": "End",
    "wf.test.node_type.human_task": "Human Task",
    "wf.test.node_type.gateway": "Gateway",
    "wf.test.node_type.agent": "Agent Node",
    "wf.agent.coordinator": "Coordinator",
    "wf.agent.supplier_auditor": "Supplier Auditor",
    "wf.agent.data_analyst": "Data Analyst",
    "wf.panel.id": "ID",
    "wf.panel.type": "Type",
    // ── Knowledge Workbench ──
    "kb.sidebar.title": "Closed-Loop Workspace",
    "kb.sidebar.ready": "Perfect Loop Ready",
    "kb.sidebar.desc": "Integration, Ontology, and Security Center data converges here to power Copilot with high-precision knowledge.",
    "kb.tab.architecture": "Research / Architecture",
    "kb.tab.sync": "Metadata Sync",
    "kb.tab.lineage": "Lineage & Impact",
    "kb.tab.ontology": "Ontology Alignment",
    "kb.tab.index": "Vector Index Builder",
    "kb.tab.rag": "RAG Simulation",
    "kb.tab.graph_sync": "Graph Sync",
    "kb.tab.graph_explore": "Graph Explorer",
    "kb.sync.title": "Multi-Modal Federated Metadata Sync Center",
    "kb.sync.syncAll": "Federated Full-Site Sync",
    "kb.sync.syncing": "Federated grid crawling...",
    "kb.sync.assetsTitle": "Three-Platform Metadata Sync List",
    "kb.sync.assetName": "Asset Name",
    "kb.sync.assetSource": "Source",
    "kb.sync.metaType": "Metadata Type",
    "kb.sync.synced": "Synced",
    "kb.sync.pending": "Pending",
    "kb.sync.outdated": "Update",
    "kb.sync.pull": "Pull Sync",
    "kb.lineage.title": "Lineage Parser & Impact Analysis",
    "kb.lineage.analyzing": "Recursively deriving downstream topology...",
    "kb.ontology.title": "Ontology-to-Physical Column Aligner",
    "kb.ontology.newEntity": "New",
    "kb.ontology.exportBtn": "Export RAG Knowledge Pack",
    "kb.ontology.saveMapping": "Save & Bind",
    "kb.ontology.addMapping": "Add Row",
    "kb.index.title": "Federated Knowledge Vector Index Engine",
    "kb.index.chunkConfig": "Chunking Config",
    "kb.index.syncBtn": "Build Vector Index",
    "kb.rag.title": "Semantic Grounding Sandbox",
    "kb.rag.searchBtn": "Search & Simulate AI",
    "kb.rag.retrieving": "Retrieving metadata vectors...",
    "kb.rag.results": "Grounded Retrieval Results",
    "kb.rag.promptTitle": "RAG Prompt Context",
    "kb.rag.outputTitle": "AI Output",
    "kb.common.close": "Close",

    // Data Workbench
    "dw.sidebar.title": "Integration Workspace",
    "dw.tab.guide": "Top-Level Design: 4 Tools into 5 Phases",
    "dw.tab.connections": "Data Sources & Connections",
    "dw.tab.syncs": "Physical Data Sync Tasks",
    "dw.tab.pipelines": "Data Transform & Pipeline",
    "dw.tab.health": "Data Quality Health Check",
    "dw.tab.lineage": "Full Chain Data Lineage Map",
    "dw.sidebar.stats": "Physical Data Monitor",
    "dw.sidebar.connections": "External Interfaces",
    "dw.sidebar.syncs": "Stream-Batch Sync Pipelines",
    "dw.sidebar.objects": "Fused Objects",
    "dw.txt.004669": "仅手动触发 (Manual)",
    "dw.txt.01b9b1": "已注入 PB 函数:",
    "dw.txt.033f47": "经推演，本轮开启内存 GC 缓冲区复用与 Web Worker 多线程并行分流后，单机 Hash Map JOIN 效率提升约",
    "dw.txt.03c868": "回收规范:",
    "dw.txt.083142": "🚀 物理引擎:",
    "dw.txt.0d63d3": "HTTP API 网关",
    "dw.txt.0d7003": "架构规划细则 (Implementation Architecture)",
    "dw.txt.0f541b": "全链路数据血缘地图",
    "dw.txt.102168": "数据源与物理连接",
    "dw.txt.1169ed": "用户主凭据 (User ID)",
    "dw.txt.118029": "常驻内存 (RAM Footprint) 上限控制",
    "dw.txt.11add3": "请选择一个物理数据同步任务查看详情",
    "dw.txt.11cefc": "物理数据同步任务",
    "dw.txt.12f07f": "，多维统计聚合算子将直接由本地 BE 分区列索引承载，彻底避免物理 Shuffle 带来的宽带阻塞瓶颈！",
    "dw.txt.12f1d0": "质检规则",
    "dw.txt.153eeb": "SQL 过滤条件:",
    "dw.txt.15e5bb": "物理网络端点",
    "dw.txt.165c7b": "最近连接校验时间",
    "dw.txt.16e578": "服务器 Host",
    "dw.txt.1988fc": "流批同步管道:",
    "dw.txt.1ad16f": "ECOS 分支控制 (Git Branch)",
    "dw.txt.1b23b5": "数据质量健康检测",
    "dw.txt.1e7bf5": "注入 PB 表达式算子",
    "dw.txt.2063a2": "限定判定阈值 (Threshold)",
    "dw.txt.226b09": "类型",
    "dw.txt.26079a": "物理数据湖 Ingress 连接器调试面板",
    "dw.txt.26a4e8": "请选择一个清洗逻辑管道",
    "dw.txt.27ae19": "预览并一键导出方案说明书",
    "dw.txt.282170": "请选择一个物理数据源查看详情",
    "dw.txt.2b6bc0": "操作",
    "dw.txt.2ce9e0": "当前物理数据源连接受阻或未注册可用数据表目录。",
    "dw.txt.2d4ed7": "240ms (优化前) &rarr;",
    "dw.txt.2fa8de": "一、ECOS 核心管道构建四大开发工具",
    "dw.txt.30609b": "180,000 rps (优化后)",
    "dw.txt.30f7dd": "连接",
    "dw.txt.310118": "Colocate 对齐激活",
    "dw.txt.311324": "Aviation Control 运维邮箱",
    "dw.txt.332103": "新建外界物理数据源连接",
    "dw.txt.3423fb": "经推演，本轮开启所有 Apache Doris 分布式列式优化后，大表 JOIN 查询延迟缩短约",
    "dw.txt.34a4de": "当前节点输出 Schema",
    "dw.txt.384142": "，杜绝了由于主线程密集运算带来的任何丢帧卡顿情况！",
    "dw.txt.39cb73": "二、官方标准数据管道构建五步法 (可交互演练环境)",
    "dw.txt.3a0fd4": "⚡ 计算引擎与调优",
    "dw.txt.3a7896": "下游落湖 (Silver)",
    "dw.txt.3a8093": "功能描述与规范定义",
    "dw.txt.3bdd08": "描述",
    "dw.txt.3cd968": "API 端点网关",
    "dw.txt.3dfa9c": "算法模型:",
    "dw.txt.3f6461": "📂 ECOS 生产级底层代码参考",
    "dw.txt.3fea7c": "状态",
    "dw.txt.4016cf": "网关 Port",
    "dw.txt.419d9f": "物理数据监控仪表",
    "dw.txt.42bc1b": "对方可读取数据表/目录列表",
    "dw.txt.445bdd": "24 次/天",
    "dw.txt.44a230": "已融合对象数:",
    "dw.txt.44d70b": "42ms (优化后)",
    "dw.txt.44e8b3": "请先修改配置或完成物理连接探测握手。",
    "dw.txt.48e387": "🟢 核心优势:",
    "dw.txt.496a4b": "最近上报版本标签",
    "dw.txt.4aa8c3": "联动警报接收路由 (Webhooks)",
    "dw.txt.4c96fe": "物理源数据表/文件夹",
    "dw.txt.52d7f4": "监控目标落湖表",
    "dw.txt.53ace4": "已启用",
    "dw.txt.558887": "Doris BE 物理查询及多维扫描延迟",
    "dw.txt.578202": "0 MB (Colocate 本地化)",
    "dw.txt.58314a": "物理源名称 (Connection Name)",
    "dw.txt.58d7c8": "集成工作区",
    "dw.txt.5ac0cc": "对方数据表/物理目录",
    "dw.txt.5c5633": "开启并行分流",
    "dw.txt.5c9d54": "列数:",
    "dw.txt.5da13f": "所有物理同步/提取任务",
    "dw.txt.5e099e": "时效时限违约事件",
    "dw.txt.5fa09f": "微批流处理每 30s 注入 (Micro-batch)",
    "dw.txt.5fcc68": "所有规则校验",
    "dw.txt.64d3b2": "所有外界物理数据源",
    "dw.txt.64d859": "行数 (Est):",
    "dw.txt.65779d": "物理数据湖源、ETL 清洗及数据血缘的一体化管理中心",
    "dw.txt.6651d2": "最近执行统计报告",
    "dw.txt.679c15": "首选数据引擎",
    "dw.txt.67d95e": "450ms (优化前) &rarr;",
    "dw.txt.6974b2": "同步计算吞吐耗时",
    "dw.txt.69ef1e": "每小时 05 分定时计算 (Hourly)",
    "dw.txt.6dd76a": "监控 ECOS 在库数据集的质量漂移，当违背阈值时触发报警或执行阻断。",
    "dw.txt.6fbcb9": "转换前 (Before Source Ingress)",
    "dw.txt.70edaa": "算子规则配置 (Operator Editor)",
    "dw.txt.721755": "检测触发阈值与报警边界",
    "dw.txt.72717e": "多核调度:",
    "dw.txt.72a256": "物理堆内存空间占用：严格控制在 12 MB 独占",
    "dw.txt.74eeaf": "物理数据源",
    "dw.txt.79a539": "MV 声明:",
    "dw.txt.7adcd8": "连接端口 (Port)",
    "dw.txt.7de8db": "数据工作台 (Data Workbench)",
    "dw.txt.8018fb": "垃圾回收 (GC GC Pause) 卡顿时间",
    "dw.txt.80aaef": "高频 Cron 计划",
    "dw.txt.811feb": "最少行数警示水位",
    "dw.txt.813a1c": "运行调度频度",
    "dw.txt.8240a1": "飞书监控报警卡片推送",
    "dw.txt.8244ee": "同步算法规范",
    "dw.txt.824885": "同步模式",
    "dw.txt.831c7d": "增量提取 (Incremental)",
    "dw.txt.84bea7": "Doris 列式存储物理空间压缩率",
    "dw.txt.88e804": "⚙️ 核心支撑组件",
    "dw.txt.8addbe": "秒级索引加速",
    "dw.txt.8be220": "时效指标监控 (SLA Freshness)",
    "dw.txt.911247": "外界物理源 (Ingress Source)",
    "dw.txt.91ab83": "新建数据质量健康检查",
    "dw.txt.952c30": "调度触发频率 (Frequency)",
    "dw.txt.957599": "选择计算引擎",
    "dw.txt.97a690": "末尾追加 (Append)",
    "dw.txt.9b600a": "正在运行物理运算模拟...",
    "dw.txt.9caecd": "字段",
    "dw.txt.9df05c": "📊 数据生命周期流转",
    "dw.txt.9f1c94": "840 MB (优化前) &rarr;",
    "dw.txt.a001a2": "更新时间",
    "dw.txt.a35326": "物理作业触发频率",
    "dw.txt.a7e407": "立即启动提取同步 (Run Ingest)",
    "dw.txt.aaf147": "主机/端点主机 (Host / URL)",
    "dw.txt.ac4313": "配属等级:",
    "dw.txt.af2c4a": "聚合粒度:",
    "dw.txt.b22078": "12,000 rps (优化前) &rarr;",
    "dw.txt.b316a5": "检测规则分类",
    "dw.txt.b35137": "当前分支:",
    "dw.txt.b36472": "作业稳定性大盘 (Stability Panel)",
    "dw.txt.b478e4": "🛠️ 管道构建与算子",
    "dw.txt.ba49ba": "拉取同步总行数",
    "dw.txt.bb0cb7": "单次平准计算延迟",
    "dw.txt.bb4a1b": "重试及退避间隔 (Retry backoff)",
    "dw.txt.bbedcc": "运行计划 & 时间周期",
    "dw.txt.bca5fe": "数据总行数校验 (Min Rows)",
    "dw.txt.bdfb20": "一键复制全套方案",
    "dw.txt.c2750e": "最大计算阻断超时 (Max Duration)",
    "dw.txt.c40508": "编译并运行管道",
    "dw.txt.c4a9c9": "表结构字段一致性校验 (Schema)",
    "dw.txt.c56266": "顶层策划：四工具融入五环节",
    "dw.txt.c59de0": "O(1) 匹配极速",
    "dw.txt.c5dda0": "外界系统集成接口 (APIs / Sources)",
    "dw.txt.c6f0b6": "数据湖目的物理表 (Raw Dataset ID)",
    "dw.txt.c8767b": "单步执行质检 rules",
    "dw.txt.ca6183": "最近一次任务时间",
    "dw.txt.cb8b5d": "平均冷启动消耗时间",
    "dw.txt.cdb140": "列字段 (Column)",
    "dw.txt.ce3ee2": "计算节点:",
    "dw.txt.d04d82": "请选择一个数据质检健康规则",
    "dw.txt.d086dc": "最大可承受空值比例 (Max Null %)",
    "dw.txt.d28316": "钉钉/企业微信工作流机器人",
    "dw.txt.d30131": "📅 SLA 调度与监控",
    "dw.txt.d32eec": "任务说明 (Task Name)",
    "dw.txt.d43c1e": "Doris 分布式节点跨节点 Shuffle 交换",
    "dw.txt.d4e181": "每小时定时",
    "dw.txt.d5588c": "全量快照 (Snapshot)",
    "dw.txt.d6aaff": "配置项:",
    "dw.txt.d7ec2d": "名称",
    "dw.txt.d85c7b": "提取任务",
    "dw.txt.d8a8a4": "复制示例",
    "dw.txt.dbe3d6": "ECOS 核心开发工具",
    "dw.txt.dd7543": "V8 内存清洗吞吐率 (Throughput)",
    "dw.txt.de8bec": "🛠️ 支撑语言:",
    "dw.txt.dec92b": "集成协议与驱动",
    "dw.txt.e23d93": "每日凌晨 02:00 (Daily batch)",
    "dw.txt.e3e567": "⚠️ 调度延滞时效性预警",
    "dw.txt.e442a8": "SLA 时效阻塞界限 (分钟)",
    "dw.txt.e4f186": "🔴 开发避坑:",
    "dw.txt.e54c87": "0 次违约 (Green)",
    "dw.txt.e6fdc9": "MPP 列存优化：节省存储空间 82%",
    "dw.txt.e77c42": "日均作业实例数",
    "dw.txt.e9bc2c": "每日定时",
    "dw.txt.ead4a7": "🚨 物理脏数据比率阻断阀值",
    "dw.txt.eb9003": "目标 S3 存储桶",
    "dw.txt.ec7002": "缩放: 100%",
    "dw.txt.eeb061": "DDL 语法项:",
    "dw.txt.eed3c7": "同步源及目标存储",
    "dw.txt.f0eff8": "格式:",
    "dw.txt.f17556": "S3 落点存储桶",
    "dw.txt.f274bd": "外界物理系统名称",
    "dw.txt.f2e8f6": "检测规则名称 (Rule Name)",
    "dw.txt.f4deb5": "ECOS 官方反模式警示 (Anti-Pattern Warning)",
    "dw.txt.f58b36": "2.45 秒",
    "dw.txt.f636a1": "测试物理握手 (Test Ingress)",
    "dw.txt.f6ebf8": "已激活",
    "dw.txt.f75e4f": "比率 &gt; 1%",
    "dw.txt.f786e8": "用户认证账号 (Username / IAM)",
    "dw.txt.f7d9ac": "外部数据接口:",
    "dw.txt.f80f8b": "关联条件 (Keys):",
    "dw.txt.fb1d84": "关键字段空值控制 (Null Check)",
    "dw.txt.fdcb6f": "数据转换与 Pipeline",
    "dw.txt.fde125": "8ms (优化后)",
    "dw.txt.fe3609": "数据库/源类别 (Type)",
    "dw.txt.ff8464": "新建物理数据拉取同步任务",

    // Ontology
    "ontology.confirm_delete_element": "Are you sure you want to delete this ontology element? This action cannot be undone.",
    "ontology.cannot_delete_pk": "Cannot delete primary key property!",
    "ontology.confirm_delete_domain": "Are you sure you want to delete domain (name)? Associated entities will be unclassified.",
  }
};

const LanguageContext = createContext<LanguageContextType | undefined>(undefined);

export const LanguageProvider: React.FC<{ children: React.ReactNode }> = ({ children }) => {
  const [locale, setLocaleState] = useState<Locale>(() => {
    // Chinese is the absolute default
    const saved = localStorage.getItem("ecos_locale");
    return (saved as Locale) || "zh";
  });

  const setLocale = (newLocale: Locale) => {
    setLocaleState(newLocale);
    localStorage.setItem("ecos_locale", newLocale);
  };

  const t = (key: string): string => {
    const translation = DICTIONARY[locale][key];
    if (translation !== undefined) {
      return translation;
    }
    // Fallback to English if missing, then to key itself
    return DICTIONARY["en"][key] ?? key;
  };

  return (
    <LanguageContext.Provider value={{ locale, setLocale, t }}>
      {children}
    </LanguageContext.Provider>
  );
};

export const useLanguage = () => {
  const context = useContext(LanguageContext);
  if (!context) {
    throw new Error("useLanguage must be used within a LanguageProvider");
  }
  return context;
};
