#!/usr/bin/env bash
set +e
echo "=== td_user cols ==="
docker exec -i ecos-postgres psql -U postgres -d sys_man -tAc "SELECT string_agg(column_name, ', ' ORDER BY ordinal_position) FROM information_schema.columns WHERE table_name='td_user';"
echo "=== admin row ==="
docker exec -i ecos-postgres psql -U postgres -d sys_man -tAc "SELECT user_id, user_name, tenant_id, status FROM td_user WHERE user_name LIKE 'admin%' LIMIT 3;"
docker exec -i ecos-postgres psql -U postgres -d sys_man -tAc "SELECT account, user_name, tenant_id, status FROM td_user LIMIT 3;"
echo "=== tenants ==="
docker exec -i ecos-postgres psql -U postgres -d sys_man -tAc "SELECT tenant_id, name, status FROM ecos_tenant LIMIT 5;"
docker exec -i ecos-postgres psql -U postgres -d sys_man -tAc "SELECT count(*) FROM ecos_tenant;"
echo "=== ontology domains ==="
docker exec -i ecos-postgres psql -U postgres -d sys_man -tAc "SELECT column_name FROM information_schema.columns WHERE table_name='ecos_ontology_domain';"
docker exec -i ecos-postgres psql -U postgres -d sys_man -tAc "SELECT count(*) FROM ecos_ontology_domain;"
echo "=== compliance rules ==="
docker exec -i ecos-postgres psql -U postgres -d sys_man -tAc "SELECT count(*) FROM sys_compliance_rule;"
docker exec -i ecos-postgres psql -U postgres -d sys_man -tAc "SELECT id, name, domain, status, enabled, version FROM sys_compliance_rule LIMIT 5;"
echo "=== decisions ==="
docker exec -i ecos-postgres psql -U postgres -d sys_man -tAc "SELECT count(*) FROM ecos_decision;"
echo "=== extraction drafts ==="
docker exec -i ecos-postgres psql -U postgres -d sys_man -tAc "SELECT column_name FROM information_schema.columns WHERE table_name='extraction_drafts';"
docker exec -i ecos-postgres psql -U postgres -d sys_man -tAc "SELECT count(*) FROM extraction_drafts;"
