server:
  port: 18089
  servlet:
    context-path: /

spring:
  application:
    name: ecos-cognitive-engine-boot
  datasource:
    url: jdbc:postgresql://localhost:5432/sys_man
    username: postgres
    password: postgres
    driver-class-name: org.postgresql.Driver

mybatis:
  type-aliases-package: com.chinacreator.gzcm.engine.cognitive2.model

management:
  endpoints:
    web:
      exposure:
        include: health,info,metrics
